<?php self::$js[] = 'registration'; ?>
<h1>Регистрация</h1>
<form name="registration">
<div><div>Email</div><input type="text" name="email"></div>
<div><div>Имя</div><input type="text" name="name"></div>
<div><div>Пароль</div><input type="password" name="password"></div>
<div><div>Повторите пароль</div><input type="password" name="repassword"></div>
<hr>
<div><input type="button" name="reg" value="Зарегестрироваться"></div>
</form>
